<?php

/**
 * Implementation of hook_menu()
 */
function olark_menu() {
  $items = array();

  $items['admin/settings/olark'] = array(
    'title' => 'Olark settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('olark_settings'),
    'access arguments' => array('administer site configuration') 
  );

  return $items;
}

/**
 * Implementation of hook_footer()
 */
function olark_footer() {
  if (!variable_get('olark_context', 0)) {
    olark_add_js();
    return variable_get('olark_code', '');
  }
  else {
    if ($plugin = context_get_plugin('reaction', 'olark_add')) {
      if ($plugin->execute()) {
        olark_add_js();
        return variable_get('olark_code', '');
      }
    }
  }
}

/**
 * Implementation of hook_context_registry().
 */
function olark_context_registry() {
  return array(
    'reactions' => array(
      'olark_add' => array(
        'title' => t('Olark'),
        'plugin' => 'olark_context_reaction_add',
        'description' => t('Add Olark chat code to the page'),
      ),
    ),
  );
}

/**
 * Notify CTools that we'll be using the plugin API with Context module
 */
function olark_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * CTools plugin API hook for Context
 */
function olark_context_plugins() {
  $plugins = array();
  $plugins['olark_context_reaction_add'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'olark') .'/plugins',
      'file' => 'olark_context_reaction_add.inc',
      'class' => 'olark_context_reaction_add',
      'parent' => 'context_reaction',
    ),
  );

  return $plugins;
}

/**
 * Settings form
 */
function olark_settings() {
  $form = array();
  $form['olark_code'] = array(
    '#type' => 'textarea',
    '#title' => t('Olark code'),
    '#description' => t("Javascript code block from Olark.com"),
    '#default_value' => variable_get('olark_code', ''),
  );
  if (module_exists('context')) {
    $form['olark_context'] = array(
      '#type' => 'checkbox',
      '#title' => t('Use <a href="!context_url">Context module</a> to choose when Olark is added to the page.'),
      '#description' => t("Javascript code block from Olark.com"),
      '#default_value' => variable_get('olark_context', 1),
    );
  }
  return system_settings_form($form);
}

function olark_add_js() {
  static $added;
  if (!isset($added)) {
    global $user;
    
    $path = drupal_get_path('module', 'olark');  
    drupal_add_js($path . '/olark.js');
    
    $setting = array('olark' => array());
    
    if ($user->uid) {
      $setting['olark']['name'] = $user->name;
      //$setting['olark']['uid'] = $user->uid;
      $setting['olark']['mail'] = $user->mail;
      $setting['olark']['userpage'] = url('user/' . $user->uid, array('absolute' => TRUE));
    }
    
    drupal_add_js($setting, 'setting');
      
    $added = TRUE;
  }
}